# Generated by Django 4.0 on 2022-01-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categorias',
            field=models.ManyToManyField(to='tienda.Categoria'),
        ),
    ]
