# Generated by Django 4.0 on 2022-01-28 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_rename_categoria_categoriaprod_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='disponibilidad',
            new_name='disponible',
        ),
    ]
