# Generated by Django 4.0 on 2022-01-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_rename_disponibilidad_producto_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categorias',
        ),
    ]
